### ISSUE TITLE
Some questions about the code

### ISSUE THREAD

**Issue by Yewx0310** [WHUIR/DiffuRec#1]
Hello, Congratulations and thank you for your work, I would like to ask you some questions about the code, mainly in model.py, when I try to read the code, i found that  in the commented out content from lines 139 to 141, the self.model_main does not exist in the entire code file, I was wondering if you could share the complete code, thank you again.

**Comment by Yuhanleeee** [comment]
Thank you for your information. I am sorry to confuse you. Lines 130 to 141 and the self.model_main in the model.py script are the initial version for score generation.  Indeed, we calculate the scores of each individual via inner product operation or routing, the two methods as we reported in equation (22) section 5.5. Consequently, we have commented out these codes for scores calculation, moving it to line 122, trainer.py scripts instead. Actually, you could also remove "scores=None" line 142. Hopefully, I could answer your questions.

**Comment by Yewx0310** [comment]
Thank you for your reply, I will read the code carefully again and thank you again for your work
